config/routes.rb
BravePosTracker::Application.routes.draw do
  resources :reinforcement_timers
  resources :corporations
  resources :control_towers
  
  get "dashboard/index"

  root :to => 'dashboard#index'

end

app/models/control_tower.rb
class ControlTower < ActiveRecord::Base
  attr_accessible :constellation_id, :corporation_id, :moon_id, :moon_name, :region_id, :solar_system_id, :type_id
  
  belongs_to :corporation
  has_one :reinforcement_timer, :dependent => :destroy
  
  validates :corporation_id,  :presence => true
  validates :moon_id,         :presence => true,  :numericality => true,  :uniqueness => true
  validates :type_id,         :presence => true,  :numericality => true
end

app/models/corporation.rb
class Corporation < ActiveRecord::Base
  attr_accessible :eve_id, :name
  has_many :control_towers
  
  validates :name,    :presence => true
  validates :eve_id,  :presence => true
end

app/models/reinforcement_timer.rb
class ReinforcementTimer < ActiveRecord::Base
  attr_accessible :expires_at, :control_tower_id
  
  belongs_to :control_tower
  validates :control_tower_id, :presence => true
  
  def expired?
    Time.now > expires_at
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/control_towers_controller.rb
class ControlTowersController < ApplicationController
  # GET /control_towers
  # GET /control_towers.json
  def index
    @control_towers = ControlTower.order(:moon_name).page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @control_towers }
    end
  end

  # GET /control_towers/1
  # GET /control_towers/1.json
  def show
    @control_tower = ControlTower.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @control_tower }
    end
  end

  # GET /control_towers/new
  # GET /control_towers/new.json
  def new
    @corporations = Corporation.all(:select => "id, name").to_json
    @control_tower = ControlTower.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @control_tower }
    end
  end

  # GET /control_towers/1/edit
  def edit
    @control_tower = ControlTower.find(params[:id])
  end

  # POST /control_towers
  # POST /control_towers.json
  def create
    @control_tower = ControlTower.new(params[:control_tower])

    respond_to do |format|
      if @control_tower.save
        format.html { redirect_to @control_tower, notice: 'Control tower was successfully created.' }
        format.json { render json: @control_tower, status: :created, location: @control_tower }
      else
        format.html { render action: "new" }
        format.json { render json: @control_tower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /control_towers/1
  # PUT /control_towers/1.json
  def update
    @control_tower = ControlTower.find(params[:id])

    respond_to do |format|
      if @control_tower.update_attributes(params[:control_tower])
        format.html { redirect_to @control_tower, notice: 'Control tower was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @control_tower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /control_towers/1
  # DELETE /control_towers/1.json
  def destroy
    @control_tower = ControlTower.find(params[:id])
    @control_tower.destroy

    respond_to do |format|
      format.html { redirect_to control_towers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/corporations_controller.rb
class CorporationsController < ApplicationController
  # GET /corporations
  # GET /corporations.json
  def index
    @corporations = Corporation.order(:name).page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @corporations }
    end
  end

  # GET /corporations/1
  # GET /corporations/1.json
  def show
    @corporation = Corporation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @corporation }
    end
  end

  # GET /corporations/new
  # GET /corporations/new.json
  def new
    @corporation = Corporation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @corporation }
    end
  end

  # GET /corporations/1/edit
  def edit
    @corporation = Corporation.find(params[:id])
  end

  # POST /corporations
  # POST /corporations.json
  def create
    @corporation = Corporation.new(params[:corporation])

    respond_to do |format|
      if @corporation.save
        format.html { redirect_to @corporation, notice: 'Corporation was successfully created.' }
        format.json { render json: @corporation, status: :created, location: @corporation }
      else
        format.html { render action: "new" }
        format.json { render json: @corporation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /corporations/1
  # PUT /corporations/1.json
  def update
    @corporation = Corporation.find(params[:id])

    respond_to do |format|
      if @corporation.update_attributes(params[:corporation])
        format.html { redirect_to @corporation, notice: 'Corporation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @corporation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /corporations/1
  # DELETE /corporations/1.json
  def destroy
    @corporation = Corporation.find(params[:id])
    @corporation.destroy

    respond_to do |format|
      format.html { redirect_to corporations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/reinforcement_timers_controller.rb
class ReinforcementTimersController < ApplicationController
  # GET /reinforcement_timers
  # GET /reinforcement_timers.json
  def index
    @reinforcement_timers = ReinforcementTimer.order(:expires_at).page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reinforcement_timers }
    end
  end

  # GET /reinforcement_timers/1
  # GET /reinforcement_timers/1.json
  def show
    @reinforcement_timer = ReinforcementTimer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reinforcement_timer }
    end
  end

  # GET /reinforcement_timers/new
  # GET /reinforcement_timers/new.json
  def new
    @reinforcement_timer = ReinforcementTimer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reinforcement_timer }
    end
  end

  # GET /reinforcement_timers/1/edit
  def edit
    @reinforcement_timer = ReinforcementTimer.find(params[:id])
  end

  # POST /reinforcement_timers
  # POST /reinforcement_timers.json
  def create
    @reinforcement_timer = ReinforcementTimer.new(params[:reinforcement_timer])

    respond_to do |format|
      if @reinforcement_timer.save
        format.html { redirect_to @reinforcement_timer, notice: 'Reinforcement timer was successfully created.' }
        format.json { render json: @reinforcement_timer, status: :created, location: @reinforcement_timer }
      else
        format.html { render action: "new" }
        format.json { render json: @reinforcement_timer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reinforcement_timers/1
  # PUT /reinforcement_timers/1.json
  def update
    @reinforcement_timer = ReinforcementTimer.find(params[:id])

    respond_to do |format|
      if @reinforcement_timer.update_attributes(params[:reinforcement_timer])
        format.html { redirect_to @reinforcement_timer, notice: 'Reinforcement timer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reinforcement_timer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reinforcement_timers/1
  # DELETE /reinforcement_timers/1.json
  def destroy
    @reinforcement_timer = ReinforcementTimer.find(params[:id])
    @reinforcement_timer.destroy

    respond_to do |format|
      format.html { redirect_to reinforcement_timers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/control_towers/_form.html.erb
<div id="control_tower_form">
  <%= javascript_tag "var corporations = #{ @corporations };" %>

  <%= form_for(@control_tower) do |f| %>
    <% if @control_tower.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@control_tower.errors.count, "error") %> prohibited this control_tower from being saved:</h2>

        <ul>
        <% @control_tower.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :corporation_id %><br />
      <%= text_field_tag 'corporation_name', nil, :autocomplete => :off, :placeholder => "corporation name", :data => { :provide =>"typeahead" } %>
    </div>
    
    <div class="field">
      <%= f.label :solar_system_id %><br />
      <%= text_field_tag 'solar_system_name', nil, :autocomplete => :off, :placeholder => "solar system name", :data => { :provide =>"typeahead" } %>
    </div>
    
    <div class="field">
      <%= f.label :moon_id %><br />
      <select id="control_tower_moon_id" name="control_tower[moon_id]"></select>
    </div>
    
    <div class="field">
      <%= f.label :type_id %><br />
      <select id="control_tower_type_id" name="control_tower[type_id]"></select>
    </div>
    
    <%= f.hidden_field :moon_name %>
    <%= f.hidden_field :corporation_id %>
    <%= f.hidden_field :region_id %>
    <%= f.hidden_field :constellation_id %>
    <%= f.hidden_field :solar_system_id %>
    
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/control_towers/edit.html.erb
<h1>Editing control_tower</h1>

<%= render 'form' %>

<%= link_to 'Show', @control_tower %> |
<%= link_to 'Back', control_towers_path %>

app/views/control_towers/index.html.erb
<div id="control_tower_index">
  <h1>Listing Control Towers</h1>

  <table class="table table-striped table-hover table-condensed">
    <tr>
      <th></th>
      <th>Corporation</th>
      <th>Tower Type</th>
      <th>Moon</th>
      <th>Solar system</th>
    </tr>

  <% @control_towers.each do |control_tower| %>
    <tr id="<%= control_tower.id %>" class="control_tower">
      <td><%= link_to 'View', control_tower %></td>
      <td><%= link_to "#{control_tower.corporation.name}", corporation_path(control_tower.corporation) %></td>
      <td class="type_id"><%= control_tower.type_id %></td>
      <td><%= control_tower.moon_name %></td>
      <td class="solar_system_name"><%= control_tower.solar_system_id %></td>
    </tr>
  <% end %>
  </table>
  
  <%= paginate @control_towers %>

  <br />

  <%= link_to 'New Control tower', new_control_tower_path %>
</div>

app/views/control_towers/new.html.erb
<h1>New Control Tower</h1>

<%= render 'form' %>

<%= link_to 'Back', control_towers_path %>

app/views/control_towers/show.html.erb
<div id="control_tower_show">
  <div id="control_tower_icon"><%= @control_tower.type_id %></div>
  
  <p>
    <b>Corporation:</b>
    <%= link_to "#{@control_tower.corporation.name}", corporation_path(@control_tower.corporation)  %>
  </p>

  <p>
    <b>Moon:</b>
    <%= @control_tower.moon_name %>
  </p>

  <div id="solar_system_info">
    <b>Solar System: </b><span id="solar_system_name"><%= @control_tower.solar_system_id %></span><br />
    <b>Constellation: </b><span id="constellation_name"><%= @control_tower.constellation_id %></span><br />
    <b>Region: </b><span id="region_name"><%= @control_tower.region_id %></span>
  </div>
  
  <br />
  
  <div id="reinforcement_timer_info">
    <b>Reinforcement Timer: </b>
    <% if @control_tower.reinforcement_timer %>
      <div>Expires at: <span id="reinforcement_timer_expires_at"><%= @control_tower.reinforcement_timer.expires_at %></span></div>
      <div>Local Time: <%= @control_tower.reinforcement_timer.expires_at.localtime %></div>
      <div id="reinforcement_timer_countdown"></div>
      <% if @control_tower.reinforcement_timer.expired? %>
        <br />
        What happened to the tower?  <%= link_to "Repaired", @control_tower.reinforcement_timer, method: :delete %> : <%= link_to "Destroyed", @control_tower, method: :delete %>
      <% end %>
    <% else %>
      <%= link_to "Add Timer", new_reinforcement_timer_path(:control_tower_id => @control_tower.id) %>
    <% end %>
  </div>

  <br />
  <%= link_to 'Back', control_towers_path %> | 
  <%= link_to 'Edit', edit_control_tower_path(@control_tower) %> | 
  <%= link_to 'Destroy', @control_tower, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/corporations/_form.html.erb
<%= form_for(@corporation) do |f| %>
  <% if @corporation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@corporation.errors.count, "error") %> prohibited this corporation from being saved:</h2>

      <ul>
      <% @corporation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Eve Corporation ID" %><br />
    <%= f.number_field :eve_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/corporations/edit.html.erb
<h1>Editing corporation</h1>

<%= render 'form' %>

<%= link_to 'Show', @corporation %> |
<%= link_to 'Back', corporations_path %>

app/views/corporations/index.html.erb
<h1>Listing Corporations</h1>

<table class="table table-striped table-hover table-condensed">
  <tr>
    <th>Name</th>
    <th>Eve ID</th>
  </tr>

<% @corporations.each do |corporation| %>
  <tr>
    <td><%= link_to "#{corporation.name}", corporation %></td>
    <td><%= corporation.eve_id %></td>
  </tr>
<% end %>
</table>

<%= paginate @corporations %>

<br />

<%= link_to 'New Corporation', new_corporation_path %>

app/views/corporations/new.html.erb
<h1>New corporation</h1>

<%= render 'form' %>

<%= link_to 'Back', corporations_path %>

app/views/corporations/show.html.erb
<div id="corporations-show">
  <b>Name:</b>
  <div id="corporation-name"><%= @corporation.name %></div>
  <b>Alliance:</b>
  <div id="corporation-alliance-name">Loading...</div>
  <b>Ticker:</b>
  <div id="corporation-ticker">Loading...</div>
  <b>Member Count:</b>
  <div id="corporation-membercount">Loading...</div>
  <b>CEO Name:</b>
  <div id="corporation-ceoname">Loading...</div>
  <b>Eve ID:</b>
  <div id="corporation-eveid"><%= @corporation.eve_id %></div>

  <% if @corporation.control_towers %>
    <table class="table table-striped table-hover table-condensed">
      <tr>
        <th>Control Towers</th>
      </tr>
      
      <% for tower in @corporation.control_towers %>
        <tr>
          <td><%= link_to "#{tower.moon_name}", control_tower_path(tower) %></td>
        </tr>
      <% end %>
    </table>
  <% end %>

  <%= link_to 'Back', corporations_path %> | 
  <%= link_to 'Edit', edit_corporation_path(@corporation) %> | 
  <%= link_to 'Destroy', @corporation, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/home/waiting.html.erb
<h1>Home#waiting</h1>
<p>Find me in app/views/home/waiting.html.erb</p>

app/views/layouts/_messages.html.erb
<div id="flash-messages">
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<%= link_to "Brave POS Tracker", root_path, :class => 'brand' %>
<ul class="nav">
  <li><%= link_to 'Reinforcement Timers', reinforcement_timers_path %></li>
  <li><%= link_to 'Control Towers', control_towers_path %></li>
  <li><%= link_to 'Corporations', corporations_path %></li>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Brave POS Tracker" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Tracking POS for many tears" %>">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/reinforcement_timers/_form.html.erb
<%= form_for(@reinforcement_timer) do |f| %>
  <% if @reinforcement_timer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reinforcement_timer.errors.count, "error") %> prohibited this reinforcement_timer from being saved:</h2>

      <ul>
      <% @reinforcement_timer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :expires_at %><br />
    <%= f.datetime_select :expires_at %>
  </div>
  
  <% @reinforcement_timer.control_tower_id = params[:control_tower_id] if params[:control_tower_id] %>
  <%= f.hidden_field :control_tower_id, :value => @reinforcement_timer.control_tower_id %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reinforcement_timers/edit.html.erb
<h1>Editing reinforcement_timer</h1>

<%= render 'form' %>

<%= link_to 'Show', @reinforcement_timer %> |
<%= link_to 'Back', reinforcement_timers_path %>

app/views/reinforcement_timers/index.html.erb
<h1>Listing Reinforcement Timers</h1>

<table class="table table-striped table-hover table-condensed">
  <tr>
    <th></th>
    <th>Expires (UTC)</th>
    <th>Expires (Local)</th>
    <th>Corporation</th>
    <th>Moon Name</th>
  </tr>

<% @reinforcement_timers.each do |reinforcement_timer| %>
  <tr class="<%= 'error' if reinforcement_timer.expired? %>">
    <td><%= link_to 'Show', reinforcement_timer %></td>
    <td><%= reinforcement_timer.expires_at %></td>
    <td><%= reinforcement_timer.expires_at.localtime %></td>
    <td><%= reinforcement_timer.control_tower.corporation.name %></td>
    <td><%= reinforcement_timer.control_tower.moon_name %></td>
  </tr>
<% end %>
</table>

<%= paginate @reinforcement_timers %>

app/views/reinforcement_timers/new.html.erb
<h1>New reinforcement_timer</h1>

<%= render 'form' %>

<%= link_to 'Back', reinforcement_timers_path %>

app/views/reinforcement_timers/show.html.erb
<div id="reinforcement_timer_show">
  <b>Reinforcement Timer For:</b><br/>
  <b>Moon: </b><%= @reinforcement_timer.control_tower.moon_name %><br />
  <b>Corp: </b><%= @reinforcement_timer.control_tower.corporation.name %>

  <br />
  <br />
  <b>Expires at:</b>
  <div id="reinforcement_timer_expires_at"><%= @reinforcement_timer.expires_at %></div>
  <div id="reinforcement_timer_countdown"></div>
  <% if @reinforcement_timer.expired? %>
  <br />
  What happened?  <%= link_to "Repaired", @reinforcement_timer, method: :delete %> : <%= link_to "Destroyed", @reinforcement_timer.control_tower, method: :delete %>
  <% end %>

  <br />
  <br />
  <%= link_to 'Back', reinforcement_timers_path %> | 
  <%= link_to 'Edit', edit_reinforcement_timer_path(@reinforcement_timer) %> | 
  <%= link_to 'Destroy', @reinforcement_timer, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>